# Generated by Django 5.1.6 on 2026-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gérant'), ('comptable', 'Comptable')], default='manager', max_length=20),
        ),
    ]
